swagger: '2.0'
info:
  title: MTI-AI Service
  version: '1.0'
  description: |-
    <b>Whiteboarding exercise for AI Engineer</b>

    Background:
    - A client requires a system that receives pictures as input and outputs a text that is found within the picture. 
    - The system must be on deployed on the cloud and the text being read may contain person identifying information (PII). 
    - The average load system is expected to be 10 requests a minute, with a burst rate of 2 requests a second. The average processing time is 20 seconds, but the core component does not guarantee to return correct results. The user expects the system to return result in 30 seconds. 
    - The user can also check the results generated in the last 7 days, but images processed beyond 7 days ago are purged from the system.

    Design an architecture for such a system on a cloud that would support the requirements.

    Consider the following:
    - API(REST API) - Discuss how client will follow an approach to communicate with the service along with load balancer which is the front end of the service.
    - Application Layer – Discuss how the worker thread or hosts that will take the input, send it to the core component, obtain the result and store result in the database .
    - Persistence Layer – Database

    Final part: explain the architectural choices to non-technical audience
  contact:
    name: MTI Vietnam
    url: 'https://ailab.mti-vietnam.vn/'
    email: service@mti-ailab.vn
  termsOfService: 'https://ailab.mti-vietnam.vn/term-service'
  license:
    name: 'https://ailab.mti-vietnam.vn/license'
    url: 'https://ailab.mti-vietnam.vn/license'
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
  - application/octet-stream
consumes:
  - application/json
paths:
  /image/async-detection:
    post:
      summary: 'Asynchronous-text detection operation [Binary]'
      operationId: post-image-async-detection-binarynn
      responses:
        '202':
          description: Accepted
          headers:
            X-Request-Id:
              description: An unique UUID string which be generated by AI-LAB gateway service! Its also use for further fetch detection result
              type: string
          schema:
            description: ''
            type: object
            properties:
              Success:
                type: object
                properties:
                  code:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - code
                  - message
            required:
              - Success
            x-examples:
              example-1:
                Success:
                  code: Ok
                  message: Detection request has accepted! client should keep retrying fetch the async-get-result every 10-seconds with X-Request-Id
          examples:
            example-success:
              Success:
                code: Ok
                message: 'Detection request has accepted! client should keep retrying fetch the async-get-result every 10-seconds with X-Request-Id:7d20b78f-5c41-440b-9dfb-e42c47f3eeb3'
        '400':
          description: Bad Request
          schema:
            description: ''
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - code
                  - message
            required:
              - error
            x-examples:
              example-1:
                error:
                  code: Unsupported-File
                  message: The file extension is invalid
          headers:
            X-Request-Id:
              type: string
              description: An unique UUID string which be generated by AI-LAB gateway service! Its also use for further fetch detection result
          examples:
            example-unsupported-file:
              error:
                code: Unsupported-File
                message: The file extension is invalid
            example-fileSize-tooLarge:
              error:
                code: FileSize-TooLarge
                message: Service only accept file less then N-MB
            example-fileSchema-invalid:
              error:
                code: fileSchema-invalid
                message: The file binary is invalid
            example-remoteUrl-notFound:
              error:
                code: remoteUrl-notFound
                message: Not found your remote image-url
        '500':
          description: Internal Server Error
          schema:
            description: ''
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                  tracingId:
                    type: string
                    minLength: 1
                required:
                  - code
                  - message
                  - tracingId
            required:
              - error
            x-examples:
              example-1:
                error:
                  code: unknown-error
                  message: Internal server error! please contact to administrator with attached tracing-id for more detail
                  tracingId: 401ddbba-21e8-11ec-9621-0242ac130002
          headers:
            X-Request-Id:
              type: string
              description: An unique UUID string which be generated by AI-LAB gateway service! Its also use for further fetch detection result
          examples:
            example-error:
              error:
                code: unknown-error
                message: Internal server error! please contact to administrator with attached tracing-id for more detail
                tracingId: 401ddbba-21e8-11ec-9621-0242ac130002
        '503':
          description: Service Unavailable! We got transient failure
          schema:
            description: ''
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - code
                  - message
            required:
              - error
            x-examples:
              example-1:
                error:
                  code: remoteUrl-notFound
                  message: Not found your remote image-url
          headers:
            X-Request-Id:
              type: string
              description: An unique UUID string which be generated by AI-LAB gateway service! Its also use for further fetch detection result
          examples:
            example-dbexception:
              error:
                code: timeout-dbexception-error
                message: Occurred an exception from database! lets retry your request bit later
            example-communicationexception-error:
              error:
                code: involkingCore-error
                message: Occurred an exception from Core service! lets retry your request bit later
      description: |
        - You can call this operation to submit text-detection asynchronously
        - This operation quickly respond http-202 and including a unique <b>X-Request-Id</b> from Header for further fetch detection result
      security:
        - API Key - 1: []
      parameters:
        - in: formData
          type: file
          name: image
      tags:
        - async-detection
  /image/async-detection/remote:
    post:
      summary: 'Asynchronous-text detection operation [Remote]'
      operationId: post-image-async-detection-remoten
      responses:
        '202':
          description: Accepted
          headers:
            X-Request-Id:
              description: An unique UUID string which be generated by AI-LAB gateway service! Its also use for further fetch detection result
              type: string
          schema:
            description: ''
            type: object
            properties:
              Success:
                type: object
                properties:
                  code:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - code
                  - message
            required:
              - Success
            x-examples:
              example-1:
                Success:
                  code: Ok
                  message: Detection request has accepted! client should keep retrying fetch the async-get-result every 10-seconds with X-Request-Id
          examples:
            example-success:
              Success:
                code: Ok
                message: 'Detection request has accepted! client should keep retrying fetch the async-get-result every 10-seconds with X-Request-Id:7d20b78f-5c41-440b-9dfb-e42c47f3eeb3'
        '400':
          description: Bad Request
          schema:
            description: ''
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - code
                  - message
            required:
              - error
            x-examples:
              example-1:
                error:
                  code: Unsupported-File
                  message: The file extension is invalid
          headers:
            X-Request-Id:
              type: string
              description: An unique UUID string which be generated by AI-LAB gateway service! Its also use for further fetch detection result
          examples:
            example-unsupported-file:
              error:
                code: Unsupported-File
                message: The file extension is invalid
            example-fileSize-tooLarge:
              error:
                code: FileSize-TooLarge
                message: Service only accept file less then N-MB
            example-fileSchema-invalid:
              error:
                code: fileSchema-invalid
                message: The file binary is invalid
            example-remoteUrl-notFound:
              error:
                code: remoteUrl-notFound
                message: Not found your remote image-url
        '500':
          description: Internal Server Error
          schema:
            description: ''
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                  tracingId:
                    type: string
                    minLength: 1
                required:
                  - code
                  - message
                  - tracingId
            required:
              - error
            x-examples:
              example-1:
                error:
                  code: unknown-error
                  message: Internal server error! please contact to administrator with attached tracing-id for more detail
                  tracingId: 401ddbba-21e8-11ec-9621-0242ac130002
          headers:
            X-Request-Id:
              type: string
              description: An unique UUID string which be generated by AI-LAB gateway service! Its also use for further fetch detection result
          examples:
            example-error:
              error:
                code: unknown-error
                message: Internal server error! please contact to administrator with attached tracing-id for more detail
                tracingId: 401ddbba-21e8-11ec-9621-0242ac130002
        '503':
          description: Service Unavailable! We got transient failure
          schema:
            description: ''
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - code
                  - message
            required:
              - error
            x-examples:
              example-1:
                error:
                  code: remoteUrl-notFound
                  message: Not found your remote image-url
          headers:
            X-Request-Id:
              type: string
              description: An unique UUID string which be generated by AI-LAB gateway service! Its also use for further fetch detection result
          examples:
            example-dbexception:
              error:
                code: timeout-dbexception-error
                message: Occurred an exception from database! lets retry your request bit later
            example-communicationexception-error:
              error:
                code: involkingCore-error
                message: Occurred an exception from Core service! lets retry your request bit later
      description: |
        - You can call this operation to submit text-detection asynchronously
        - This operation quickly respond http-202 and including a unique <b>X-Request-Id</b> from Header for further fetch detection result
      security:
        - API Key - 1: []
      parameters:
        - in: body
          name: body
          schema:
            description: ''
            type: object
            properties:
              imageUrl:
                type: string
                minLength: 1
            required:
              - imageUrl
            x-examples:
              example-1:
                imageUrl: 'https://mti-vietnam.vn/img/image-lunaluna-big@2x.jpg'
          description: provide specific image url
          x-examples:
            example-url:
              imageUrl: 'https://mti-vietnam.vn/img/image-lunaluna-big@2x.jpg'
      tags:
        - async-detection
    parameters: []
  /image/result:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-image-result-fetch
      description: |-
        - You can call this operation to fetch a result for a specific async-detection
        - Given <b>X-detection-Id</b> from previous async-detection response
    parameters: []
definitions: {}
basePath: /ai-lab
securityDefinitions:
  API Key - 1:
    name: API Key
    type: apiKey
    in: query
security:
  - API Key - 1: []
